### ISSUE TITLE
any chance to share the webpage source as well?

### ISSUE THREAD

**Issue by Lord255** [tclscripts/BlackIP-TCL-script#1]
so.. as far as i can see, this script dies if the webpage goes off one day.
would be nice to have the webpage as well, so everyone who has a webserver could serve the page itself too.

any chance to get the page source as well?
thx.

**Comment by DanielVoipan** [comment]
Well the source isn't mine to give, I just found it and get info from it. Until now it's a reliable source and quite stable but as every site it has its up and downs. I'm sorry for this inconvenience.

**Comment by Lord255** [comment]
oh well. no probs of course, i just thought it's your thing. :)
my prob is that in this way this is not so reliable.
and now i see that i opened this ticket to a wrong repo. lol :<
i wanted to open this "issue" to your youtubeurl title script. :)
https://github.com/tclscripts/YoutubeTitle

the questionable website is:
http://youtubesongname.000webhostapp.com

my prob is that the domain comes from a free site:
https://www.000webhost.com/
so it's not really reliable as far as i'm concerned.
but so.. do you have the source for that page?:)

sorry for opening this in the wrong place.

**Comment by DanielVoipan** [comment]
sure, specify an email and i will send you the source.

**Comment by Lord255** [comment]
did you get my mail address?
probably git sent you a mail?:)
thx.

**Comment by DanielVoipan** [comment]
i sent you an email.

**Comment by Lord255** [comment]
nice. thank you a lot! :)
this will make a batter use of the script, since i can use localhost in the script (no need to relay on 3rd party). :)
i really wish you consider adding this to your repo there, cuz if someone has also a webserver, they should adjust the tcl to localhost instead of the 3rd party url. :)
by the way nice work and thank you very much for the sharing of the source of the page itself too. :)

<5

**Comment by Jean-Paul-lopez** [comment]
Hello,

http://youtubesongname.000webhostapp.com/ is not responding. Can I get the source code for index.php too, so I can host it on my own server?

**Comment by Jean-Paul-lopez** [comment]
Hi, forget about it, it worked again and I saw what it needs for parsing. I created my own output file.
